### ISSUE TITLE
How to use in Blade Template ?

### ISSUE THREAD

**Issue by H4xl0r** [stidges/laravel-country-flags#5]
Hey there, 
sorry for asking simple questions, but how could i use those flags inside a blade template ? 

i ran `composer require stidges/laravel-country-flags`  to  install it and `npm install` and `npm run dev `

if i use something like `{{ country_flag(strtoupper(app()->getLocale())) }}`

it just shows up the Locale name like EN

what did i miss :-) ?
@stidges

**Comment by stidges** [comment]
Hi, are you on Windows by any chance? Unfortunately the country flag emoji don't work on Windows

**Comment by H4xl0r** [comment]
Yep Windows , any other way or wrong package ? :-)

found another way : https://github.com/lipis/flag-icon-css

`<span class="flag-icon flag-icon-{{ strtolower(app()->getLocale()) }}"></span>`
